### PR TITLE
Create Page as per mock up

### PR DESCRIPTION
**Pull request by AliHanifdev1**
Issue no: https://github.com/CoalAI/ganttissues/issues/20

### CODE REVIEW

**Review by MKRNaqeebi — CHANGES_REQUESTED** [review]
delete all hard-coded variables and rename any variable to a proper name

for example, there are usernames hard code and variable select1 needs a proper name

**Comment by AliHanifdev1** [comment]
> there are usernames hard code

@MKRNaqeebi  i will change the select variable name but i did not understand where username is hard coded

**Comment by MKRNaqeebi** [comment]
@AliHanifdev1 
https://github.com/MKRNaqeebi/MKRNaqeebi/pull/9/files#diff-79f6644f26bdf464146971fb729488a669aa7ee41953838ee2ef61c252046414L40

also check yourself if you found anything else

**Comment by AliHanifdev1** [comment]
> @AliHanifdev1 https://github.com/MKRNaqeebi/MKRNaqeebi/pull/9/files#diff-79f6644f26bdf464146971fb729488a669aa7ee41953838ee2ef61c252046414L40
> 
> also check yourself if you found anything else

got it thank you @MKRNaqeebi  bhai

**Comment by MKRNaqeebi** [comment]
@AliHanifdev1 run this PR and test it and check UX as well

**Review by MKRNaqeebi — CHANGES_REQUESTED** [review]
getting 404 without fetching or providing org
also do not have extra change (if you want to formate make separate PR)

**Comment by AliHanifdev1** [comment]
> getting 404 without fetching or providing org also do not have extra change (if you want to formate make separate PR)

image
done

**Review by MKRNaqeebi — APPROVED** [review]
looks good

**Pull request merged**
